global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: "myapp"
    static_configs:
      - targets: ["myapp-service:8080"]
